---
- name: Install the logwatch
  apt: 
    name: logwatch 
    state: present
  tags:
    - logwatch

- name: Configure logwatch
  template: 
    src: logwatch.conf.j2 
    dest: /etc/logwatch/conf/logwatch.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - logwatch
